<?php

namespace App\Database\Seeds;


use CodeIgniter\Database\Seeder;

class apprenticeTestSeed extends Seeder
{

    public function insertUsers() {
        $users=[
            array (
                'id' => '3',
                'fk_user_type' => '1',
                'username' => 'admin2',
                'password' => '$2y$10$tUB5R1MGgbO.zD//WArnceTY8IgnFkVVsudIdHBxIrEXJ2z3WBvcK',
                'archive' => NULL,
                'date_creation' => '2020-07-09 08:11:05',
            ),
            array (
                'id' => '4',
                'fk_user_type' => '2',
                'username' => 'FormateurDev',
                'password' => '$2y$10$Q3H8WodgKonQ60SIcu.eWuVKXmxqBw1X5hMpZzwjRKyCTB1H1l.pe',
                'archive' => NULL,
                'date_creation' => '2020-07-09 13:15:24',
            ),
            array (
                'id' => '5',
                'fk_user_type' => '2',
                'username' => 'FormateurSysteme',
                'password' => '$2y$10$Br7mIRYfLufWkrSpi2SyB.Wz0vHZQp7dQf7f2bKy5i/CkhHomSvli',
                'archive' => NULL,
                'date_creation' => '2020-07-09 13:15:47',
            ),
            array (
                'id' => '6',
                'fk_user_type' => '3',
                'username' => 'ApprentiDev',
                'password' => '$2y$10$6TLaMd5ljshybxANKgIYGOjY0Xur9EgdzcEPy1bgy2b8uyWYeVoEm',
                'archive' => NULL,
                'date_creation' => '2020-07-09 13:16:05',
            ),
            array (
                'id' => '7',
                'fk_user_type' => '3',
                'username' => 'ApprentiSysteme',
                'password' => '$2y$10$0ljkGcDQpTc0RDaN7Y2XcOhS8OB0t0QIhquLv9NcR79IVO9rCR/0.',
                'archive' => NULL,
                'date_creation' => '2020-07-09 13:16:27',
            ),
            array (
                'id' => '8',
                'fk_user_type' => '2',
                'username' => 'FormateurOperateur',
                'password' => '$2y$10$SbMYPxqnngLjxVGlG4hW..lrc.pr5Dd74nY.KqdANtEESIvmGRpWi',
                'archive' => NULL,
                'date_creation' => '2020-07-09 13:24:22',
            ),
            array (
                'id' => '9',
                'fk_user_type' => '3',
                'username' => 'ApprentiOperateur',
                'password' => '$2y$10$jPNxV2ZZ6Il2LiBQ.CWhNOoud6NsMRFILwHN8kpD410shWeiGpuxK',
                'archive' => NULL,
                'date_creation' => '2020-07-09 13:24:45',
            ),
        ];
        foreach ($users as $user){
            $this->db->table('user')->insert($user);
        }
    }

    public function insertUserCourses() {
        $user_course = array(
            # dév
            array('id' => '1','fk_user' => '6','fk_course_plan' => '6','fk_status' => '1','date_begin' => '2020-07-09','date_end' => '0000-00-00'),
            # sys
            array('id' => '2','fk_user' => '7','fk_course_plan' => '5','fk_status' => '1','date_begin' => '2020-07-09','date_end' => '0000-00-00'),
            # op
            array('id' => '3','fk_user' => '9','fk_course_plan' => '4','fk_status' => '1','date_begin' => '2020-07-09','date_end' => '0000-00-00')
        );
        foreach ($user_course as $user_coursee){
            $this->db->table('user_course')->insert($user_coursee);
        }
    }

    public function insertTrainerApprentice() {
        $trainer_apprentice = array(
            array('id' => '2','fk_trainer' => '4','fk_apprentice' => '6'),
            array('id' => '3','fk_trainer' => '5','fk_apprentice' => '7'),
            array('id' => '4','fk_trainer' => '8','fk_apprentice' => '9')
        );
        foreach ($trainer_apprentice as $trainer_apprenticee)
        $this->db->table('trainer_apprentice')->insert($trainer_apprenticee);
    }

    public function insertAcquisisitionStatus() {
        $acquisition_status = array(
            array('id' => '1', 'fk_objective' => '1', 'fk_user_course' => '1',
            'fk_acquisition_level' => '2'),
            array('id' => '2', 'fk_objective' => '2', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '3', 'fk_objective' => '3', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '4', 'fk_objective' => '507', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '5', 'fk_objective' => '508', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '6', 'fk_objective' => '509', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '7', 'fk_objective' => '510', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '8', 'fk_objective' => '511', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '9', 'fk_objective' => '512', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '10', 'fk_objective' => '513', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '11', 'fk_objective' => '514', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '12', 'fk_objective' => '515', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '13', 'fk_objective' => '516', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '14', 'fk_objective' => '517', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '15', 'fk_objective' => '518', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '16', 'fk_objective' => '519', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '17', 'fk_objective' => '520', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '18', 'fk_objective' => '521', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '19', 'fk_objective' => '522', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '20', 'fk_objective' => '523', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '21', 'fk_objective' => '524', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '22', 'fk_objective' => '525', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '23', 'fk_objective' => '526', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '24', 'fk_objective' => '527', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '25', 'fk_objective' => '528', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '26', 'fk_objective' => '529', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '27', 'fk_objective' => '530', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '28', 'fk_objective' => '531', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '29', 'fk_objective' => '532', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '30', 'fk_objective' => '533', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '31', 'fk_objective' => '534', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '32', 'fk_objective' => '535', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '33', 'fk_objective' => '536', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '34', 'fk_objective' => '537', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '35', 'fk_objective' => '538', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '36', 'fk_objective' => '539', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '37', 'fk_objective' => '540', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '38', 'fk_objective' => '541', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '39', 'fk_objective' => '542', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '40', 'fk_objective' => '543', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '41', 'fk_objective' => '544', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '42', 'fk_objective' => '545', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '43', 'fk_objective' => '546', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '44', 'fk_objective' => '547', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '45', 'fk_objective' => '548', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '46', 'fk_objective' => '549', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '47', 'fk_objective' => '550', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '48', 'fk_objective' => '551', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '49', 'fk_objective' => '552', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '50', 'fk_objective' => '553', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '51', 'fk_objective' => '554', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '52', 'fk_objective' => '555', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '53', 'fk_objective' => '556', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '54', 'fk_objective' => '557', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '55', 'fk_objective' => '558', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '56', 'fk_objective' => '559', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '57', 'fk_objective' => '560', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '58', 'fk_objective' => '561', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '59', 'fk_objective' => '562', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '60', 'fk_objective' => '563', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '61', 'fk_objective' => '564', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '62', 'fk_objective' => '565', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '63', 'fk_objective' => '566', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '64', 'fk_objective' => '567', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '65', 'fk_objective' => '568', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '66', 'fk_objective' => '569', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '67', 'fk_objective' => '570', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '68', 'fk_objective' => '571', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '69', 'fk_objective' => '572', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '70', 'fk_objective' => '573', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '71', 'fk_objective' => '574', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '72', 'fk_objective' => '575', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '73', 'fk_objective' => '576', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '74', 'fk_objective' => '577', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '75', 'fk_objective' => '578', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '76', 'fk_objective' => '579', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '77', 'fk_objective' => '580', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '78', 'fk_objective' => '581', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '79', 'fk_objective' => '582', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '80', 'fk_objective' => '583', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '81', 'fk_objective' => '584', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '82', 'fk_objective' => '585', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '83', 'fk_objective' => '586', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '84', 'fk_objective' => '587', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '85', 'fk_objective' => '588', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '86', 'fk_objective' => '589', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '87', 'fk_objective' => '590', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '88', 'fk_objective' => '591', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '89', 'fk_objective' => '592', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '90', 'fk_objective' => '593', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '91', 'fk_objective' => '594', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '92', 'fk_objective' => '595', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '93', 'fk_objective' => '596', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '94', 'fk_objective' => '597', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '95', 'fk_objective' => '598', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '96', 'fk_objective' => '599', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '97', 'fk_objective' => '600', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '98', 'fk_objective' => '601', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '99', 'fk_objective' => '602', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '100', 'fk_objective' => '603', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '101', 'fk_objective' => '604', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '102', 'fk_objective' => '605', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '103', 'fk_objective' => '606', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '104', 'fk_objective' => '607', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '105', 'fk_objective' => '608', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '106', 'fk_objective' => '609', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '107', 'fk_objective' => '610', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '108', 'fk_objective' => '611', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '109', 'fk_objective' => '612', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '110', 'fk_objective' => '613', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '111', 'fk_objective' => '614', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '112', 'fk_objective' => '615', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '113', 'fk_objective' => '616', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '114', 'fk_objective' => '617', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '115', 'fk_objective' => '618', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '116', 'fk_objective' => '619', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '117', 'fk_objective' => '620', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '118', 'fk_objective' => '621', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '119', 'fk_objective' => '622', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '120', 'fk_objective' => '623', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '121', 'fk_objective' => '624', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '122', 'fk_objective' => '625', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '123', 'fk_objective' => '626', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '124', 'fk_objective' => '627', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '125', 'fk_objective' => '628', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '126', 'fk_objective' => '629', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '127', 'fk_objective' => '630', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '128', 'fk_objective' => '631', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '129', 'fk_objective' => '632', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '130', 'fk_objective' => '633', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '131', 'fk_objective' => '634', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '132', 'fk_objective' => '635', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '133', 'fk_objective' => '636', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '134', 'fk_objective' => '637', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '135', 'fk_objective' => '638', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '136', 'fk_objective' => '639', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '137', 'fk_objective' => '640', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '138', 'fk_objective' => '641', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '139', 'fk_objective' => '642', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '140', 'fk_objective' => '643', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '141', 'fk_objective' => '644', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '142', 'fk_objective' => '645', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '143', 'fk_objective' => '646', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '144', 'fk_objective' => '647', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '145', 'fk_objective' => '648', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
            array('id' => '146', 'fk_objective' => '649', 'fk_user_course' => '1',
            'fk_acquisition_level' => '1'),
        );
        foreach ($acquisition_status as $acquisitionStatuse){
            $this->db->table('acquisition_status')
                     ->insert($acquisitionStatuse);
        }
    }

    public function run() {
        $this->insertUserCourses();
        $this->insertUsers();
        $this->insertTrainerApprentice();
        $this->insertAcquisisitionStatus();
    }

}
